spring:
  h2:
    console:
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yml
    drop-first: false
    default-schema: public
    database-change-log-table: APP_DBCHANGELOG
    database-change-log-lock-table: APP_DBCHANGELOGLOCK


  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
server:
  port: 8090

endpoints:
  serpapi:
    url: https://serpapi.com/search



