CREATE USER IF NOT EXISTS "SA" SALT 'e6f99092c674ce03' HASH '46f36bf04ee75bafee7ac0b987bfb6a9818d396a6ab21a8d0f0a22c193082684' ADMIN;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_0ABE31F1_086D_46F1_BFF3_99F8C207CD0F" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_5E786858_0082_4C2E_A798_01C91A572C05" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_7E3E7D0B_80FB_4A7A_9573_06AABE4EC1CD" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D6EED8FA_CCF9_4C7D_9159_2DE8382BB032" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_C4426F51_655F_4EFB_8630_8456CB685372" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_AD5B26F6_B378_43EA_9574_36D9FBA06A3A" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_C7A8E376_62BE_49C8_88CB_9ECCD04A6FC2" START WITH 1 BELONGS_TO_TABLE;
CREATE MEMORY TABLE "PUBLIC"."ACCOUNT"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_5E786858_0082_4C2E_A798_01C91A572C05" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_5E786858_0082_4C2E_A798_01C91A572C05",
    "ACCOUNT_ID" VARCHAR(255),
    "ACCOUNT_NAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."ACCOUNT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ACCOUNT;
CREATE MEMORY TABLE "PUBLIC"."APP_USER"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_7E3E7D0B_80FB_4A7A_9573_06AABE4EC1CD" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_7E3E7D0B_80FB_4A7A_9573_06AABE4EC1CD",
    "FIN_CODE" VARCHAR(255),
    "PHONE_NUMBER" VARCHAR(255),
    "USER_ID" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."APP_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.APP_USER;
CREATE MEMORY TABLE "PUBLIC"."CARD"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_C7A8E376_62BE_49C8_88CB_9ECCD04A6FC2" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_C7A8E376_62BE_49C8_88CB_9ECCD04A6FC2",
    "BALANCE" DECIMAL(19, 2),
    "CARD_ID" VARCHAR(255),
    "CARD_NAME" VARCHAR(255),
    "CARD_NUMBER" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."CARD" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CARD;
CREATE MEMORY TABLE "PUBLIC"."CATEGORY"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_C4426F51_655F_4EFB_8630_8456CB685372" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_C4426F51_655F_4EFB_8630_8456CB685372",
    "CATEGORY_ID" VARCHAR(255),
    "KEYWORD" VARCHAR(255),
    "MCC" VARCHAR(255),
    "NAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CATEGORY;
CREATE MEMORY TABLE "PUBLIC"."OTP"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_AD5B26F6_B378_43EA_9574_36D9FBA06A3A" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_AD5B26F6_B378_43EA_9574_36D9FBA06A3A",
    "CREATION_DATE" VARCHAR(255),
    "OTP" VARCHAR(255),
    "OTP_ID" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."OTP" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_13" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.OTP;
CREATE MEMORY TABLE "PUBLIC"."REL_ACCOUNT_WITH_USER"(
    "USER_ID" BIGINT,
    "ACCOUNT_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_ACCOUNT_WITH_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1E" PRIMARY KEY("ACCOUNT_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REL_ACCOUNT_WITH_USER;
CREATE MEMORY TABLE "PUBLIC"."REL_CARD_WITH_ACCOUNT"(
    "ACCOUNT_ID" BIGINT,
    "CARD_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_CARD_WITH_ACCOUNT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("CARD_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REL_CARD_WITH_ACCOUNT;
CREATE MEMORY TABLE "PUBLIC"."REL_OTP_WITH_USER"(
    "USER_ID" BIGINT,
    "OTP_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_OTP_WITH_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("OTP_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REL_OTP_WITH_USER;
CREATE MEMORY TABLE "PUBLIC"."REL_TRANSACTION_WITH_ACCOUNT_FROM"(
    "ACCOUNT_ID" BIGINT,
    "TRANSACTION_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_TRANSACTION_WITH_ACCOUNT_FROM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("TRANSACTION_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REL_TRANSACTION_WITH_ACCOUNT_FROM;
CREATE MEMORY TABLE "PUBLIC"."REL_TRANSACTION_WITH_CATEGORY"(
    "CATEGORY_ID" BIGINT,
    "TRANSACTION_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_TRANSACTION_WITH_CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("TRANSACTION_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REL_TRANSACTION_WITH_CATEGORY;
CREATE MEMORY TABLE "PUBLIC"."REL_TRANSACTION_WITH_USER"(
    "USER_ID" BIGINT,
    "TRANSACTION_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_TRANSACTION_WITH_USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_F" PRIMARY KEY("TRANSACTION_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REL_TRANSACTION_WITH_USER;
CREATE MEMORY TABLE "PUBLIC"."REL_USER_ROLE"(
    "USER_ID" BIGINT NOT NULL,
    "ROLE_ID" BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REL_USER_ROLE;
CREATE MEMORY TABLE "PUBLIC"."REL_USER_WITH_PRIMARY_CATEGORY"(
    "CATEGORY_ID" BIGINT,
    "USER_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_USER_WITH_PRIMARY_CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_70" PRIMARY KEY("USER_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REL_USER_WITH_PRIMARY_CATEGORY;
CREATE MEMORY TABLE "PUBLIC"."REL_USER_WITH_SECONDARY_CATEGORY"(
    "CATEGORY_ID" BIGINT,
    "USER_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."REL_USER_WITH_SECONDARY_CATEGORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_10" PRIMARY KEY("USER_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.REL_USER_WITH_SECONDARY_CATEGORY;
CREATE MEMORY TABLE "PUBLIC"."ROLE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_D6EED8FA_CCF9_4C7D_9159_2DE8382BB032" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D6EED8FA_CCF9_4C7D_9159_2DE8382BB032",
    "ROLE_NAME" VARCHAR(255),
    "ROLE_ID" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."ROLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ROLE;
CREATE MEMORY TABLE "PUBLIC"."TRANSACTION"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_0ABE31F1_086D_46F1_BFF3_99F8C207CD0F" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_0ABE31F1_086D_46F1_BFF3_99F8C207CD0F",
    "AMOUNT" DECIMAL(19, 2),
    "DATE_TIME" TIMESTAMP,
    "TRANSACTION_ID" VARCHAR(255),
    "TRANSACTION_TYPE" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."TRANSACTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_FF" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TRANSACTION;
ALTER TABLE "PUBLIC"."REL_TRANSACTION_WITH_CATEGORY" ADD CONSTRAINT "PUBLIC"."FKGD1O6XGI9BD7AGBSJ7GV10JJR" FOREIGN KEY("TRANSACTION_ID") REFERENCES "PUBLIC"."TRANSACTION"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_ACCOUNT_WITH_USER" ADD CONSTRAINT "PUBLIC"."FK8U34UE8C9YKR0FPB8I7BCPSNB" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."APP_USER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_USER_WITH_PRIMARY_CATEGORY" ADD CONSTRAINT "PUBLIC"."FKM31RWHB1Q5FTS137M4FFK4EOO" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."APP_USER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_TRANSACTION_WITH_CATEGORY" ADD CONSTRAINT "PUBLIC"."FKFW3RFF16OEOWQAC3M9F8W2JOU" FOREIGN KEY("CATEGORY_ID") REFERENCES "PUBLIC"."CATEGORY"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_CARD_WITH_ACCOUNT" ADD CONSTRAINT "PUBLIC"."FKHA5PGCR9P1KR62WLTFJ0TODPW" FOREIGN KEY("CARD_ID") REFERENCES "PUBLIC"."CARD"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_TRANSACTION_WITH_ACCOUNT_FROM" ADD CONSTRAINT "PUBLIC"."FKSVKGINKEQI0TTBXUHCQEMGDMV" FOREIGN KEY("TRANSACTION_ID") REFERENCES "PUBLIC"."TRANSACTION"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_USER_WITH_PRIMARY_CATEGORY" ADD CONSTRAINT "PUBLIC"."FK3OXJPLN44QG871XMLOL15FDRN" FOREIGN KEY("CATEGORY_ID") REFERENCES "PUBLIC"."CATEGORY"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_TRANSACTION_WITH_USER" ADD CONSTRAINT "PUBLIC"."FK6G3W5E2WP2EO2CIKKOR3XEDIC" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."APP_USER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_OTP_WITH_USER" ADD CONSTRAINT "PUBLIC"."FKQYTALVOLRPVQIMQUI8QOB5P29" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."APP_USER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_USER_ROLE" ADD CONSTRAINT "PUBLIC"."FK2R78EX0V2JHY77YL7L5YM4D41" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."APP_USER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_OTP_WITH_USER" ADD CONSTRAINT "PUBLIC"."FKRMEBCVV1LNWF8P2SEDR4MQG9W" FOREIGN KEY("OTP_ID") REFERENCES "PUBLIC"."OTP"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_CARD_WITH_ACCOUNT" ADD CONSTRAINT "PUBLIC"."FK15QK6STCK99EY252210M3F0VU" FOREIGN KEY("ACCOUNT_ID") REFERENCES "PUBLIC"."ACCOUNT"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_USER_WITH_SECONDARY_CATEGORY" ADD CONSTRAINT "PUBLIC"."FKDS4FYDW0H7AJDIFQLYMP2VRYX" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."APP_USER"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_TRANSACTION_WITH_USER" ADD CONSTRAINT "PUBLIC"."FK2JMDIYSBLK5MU28T87FGSOR27" FOREIGN KEY("TRANSACTION_ID") REFERENCES "PUBLIC"."TRANSACTION"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_USER_ROLE" ADD CONSTRAINT "PUBLIC"."FK1UXDUYL9A5VAA3269V64SEYE" FOREIGN KEY("ROLE_ID") REFERENCES "PUBLIC"."ROLE"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_USER_WITH_SECONDARY_CATEGORY" ADD CONSTRAINT "PUBLIC"."FK4O594F0S1CX9RVX2JOKMQ8PB8" FOREIGN KEY("CATEGORY_ID") REFERENCES "PUBLIC"."CATEGORY"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_TRANSACTION_WITH_ACCOUNT_FROM" ADD CONSTRAINT "PUBLIC"."FKCT2EENUBL32K2TSLDAOTQD0ST" FOREIGN KEY("ACCOUNT_ID") REFERENCES "PUBLIC"."ACCOUNT"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."REL_ACCOUNT_WITH_USER" ADD CONSTRAINT "PUBLIC"."FK63XMUCW1LXTTLJRFFWBKT99HD" FOREIGN KEY("ACCOUNT_ID") REFERENCES "PUBLIC"."ACCOUNT"("ID") NOCHECK;